export const POST_FETCH_ALL_REQUEST = 'POST_FETCH_ALL_REQUEST';
export const POST_FETCH_ALL_SUCCESS = 'POST_FETCH_ALL_SUCCESS';
export const POST_FETCH_ALL_FAIL = 'POST_FETCH_ALL_FAIL';

export const POST_FETCH_SINGLE_REQUEST = 'POST_FETCH_SINGLE_REQUEST';
export const POST_FETCH_SINGLE_SUCCESS = 'POST_FETCH_SINGLE_SUCCESS';
export const POST_FETCH_SINGLE_FAIL = 'POST_FETCH_SINGLE_FAIL';
